build and test docker

diff --git a/.github/workflows/dockerhub.yml b/.github/workflows/dockerhub.yml
--- a/.github/workflows/dockerhub.yml
+++ b/.github/workflows/dockerhub.yml
@@ -26,29 +26,32 @@ jobs:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     
-    - name: Build Docker image and Test
+    - name: Build Docker image
+      id: build_image
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile
         push: false
-        tags: |
-          mymi14s/quotes-api:${{ github.run_number }}
-          mymi14s/quotes-api:latest
-        run: |
-            docker images
-            if docker image ls | grep -q mymi14s/quotes-api; then
-                echo "Image found"
-            else
-                echo "Image not found"
-                exit 1
-            fi
-            docker run -d --name=quotes-api-test -p8000:8000 mymi14s/quotes-api:latest
-            sleep 10  # Give the container time to start up
-            curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep 200 || exit 1
-            docker logs quotes-api-test
-            docker stop quotes-api-test
-            docker rm quotes-api-test
+        tags: mymi14s/quotes-api:latest
+        
+          
+    - name: Test Docker image
+      id: test_image
+      run: |
+        docker images
+        if docker images | grep -q mymi14s/quotes-api; then
+            echo "Image found"
+        else
+            echo "Image not found"
+            exit 1
+        fi
+        docker run -d --name=quotes-api-test -p8000:8000 mymi14s/quotes-api:latest
+        sleep 10  # Give the container time to start up
+        curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep 200 || exit 1
+        docker logs quotes-api-test
+        docker stop quotes-api-test
+        docker rm quotes-api-test
 
     - name: Build and push Docker image
       if: github.ref == 'refs/heads/production' && github.event_name == 'merge'
